[package]
name = "civmap-render"
version = "0.1.0"
edition = "2021"
authors = ["Gjum <code.gjum@gmail.com>"]

[dependencies]
byteorder = "~1.4.3"
lazy_static = "~1.4.0"
lodepng = "~3.4.7"
serde = { version = "~1.0.137", features = ["derive"] }
serde_json = "~1.0.81"
