modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "${mod_issues_url}"
license = "${copyright_licence}"

[[mods]]
modId = "mapsync"
version = "${mod_version}"
displayName = "${mod_display_name}"
description = "${mod_description}"
displayURL = "${mod_home_url}"
authors = "${mod_authors}"
#logoFile = ""

[[dependencies.mapsync]]
modId = "forge"
mandatory = true
versionRange = "[${forge_major_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mapsync]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
