modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "mapsync"
version = "${version}"
displayName = "Map Sync"
authors = "Gjum"
description = '''
Sync map data with others instantly.
'''
#logoFile = ""

[[dependencies.mapsync]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mapsync]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "CLIENT"
