name: Build+Test Server

on:
  push:
    paths:
      - "mapsync-server/**/*"
  pull_request:
    paths:
      - "mapsync-server/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          package_json_file: ./mapsync-server/package.json
          cache_dependency_path: ./mapsync-server/pnpm-lock.yaml

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./mapsync-server/.nvmrc
          cache: "pnpm"
          cache-dependency-path: ./mapsync-server/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install
        working-directory: ./mapsync-server

      - name: Build
        run: pnpm run build
        working-directory: ./mapsync-server

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          package_json_file: ./mapsync-server/package.json
          cache_dependency_path: ./mapsync-server/pnpm-lock.yaml

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./mapsync-server/.nvmrc
          cache: "pnpm"
          cache-dependency-path: ./mapsync-server/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install
        working-directory: ./mapsync-server

      - name: Test
        run: pnpm run test
        working-directory: ./mapsync-server
