name: Build+Test Server

on:
  push:
    paths:
      - "server/**/*"
  pull_request:
    paths:
      - "server/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using nodejs v18
        uses: actions/setup-node@v6
        with:
          node-version: "18"
      - run: npm install
        working-directory: ./server
      - run: npm run build
        working-directory: ./server
      - run: npm run test
        working-directory: ./server
