name: Build+Test Server

on:
  push:
    paths:
      - "server/**/*"
  pull_request:
    paths:
      - "server/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.2.15", "latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.version }}
      - run: bun install
        working-directory: ./server
      - run: bun test
        working-directory: ./server
