name: Build+Test Server

on:
  push:
    paths:
      - "server/**/*"
  pull_request:
    paths:
      - "server/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["lts/*", "latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Use latest Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          # cache: "yarn"
      - run: yarn
        working-directory: ./server
      - run: yarn build
        working-directory: ./server
      - run: yarn test
        working-directory: ./server
