name: Build+Test Server

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: cd server && yarn
    - run: cd server && yarn build
    - run: cd server && yarn test
